name: conduit
description: "Client IRCv3 multi-plateforme"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Routing
  go_router: ^17.0.1

  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # Database
  drift: ^2.25.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.31

  # Desktop Window
  window_manager: ^0.4.3

  # Utils
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.2.3
  json_serializable: ^6.9.4
  riverpod_generator: ^3.0.3
  mocktail: ^1.0.4
  drift_dev: ^2.25.0

flutter:
  uses-material-design: true
